// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	service2 "github.com/qccoo/w4/app/internal/biz/service"
	"github.com/qccoo/w4/app/internal/data"
	"github.com/qccoo/w4/app/internal/service"
)

// Injectors from wire.go:

func InitializeServer() (service.Server, error) {
	imageRepoImpl := data.NewRepo()
	imageService := service2.NewImageService(imageRepoImpl)
	server := service.NewServer(imageService)
	return server, nil
}
